version: "3.8"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:8081"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    env_file:
      - .env

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:8082"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./start.sh:/start.sh:ro
    env_file:
      - .env
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - INACTIVE_POOL=${INACTIVE_POOL}
    depends_on:
      - app_blue
      - app_green
    restart: always
    command: ["/bin/sh", "/start.sh"]
