services:
  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: blue-green-app_blue
    environment:
      - X_APP_POOL=blue
      - X_RELEASE_ID=${ACTIVE_RELEASE}
    ports:
      - "8081:3000"
    #healthcheck:
     # test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      #interval: 10s
      #timeout: 5s
      #retries: 3

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: blue-green-app_green
    environment:
      - X_APP_POOL=green
      - X_RELEASE_ID=${INACTIVE_RELEASE}
    ports:
      - "8082:3000"
    #healthcheck:
     # test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      #interval: 10s
      #timeout: 5s
      #retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: blue-green-nginx
    ports:
      - "8080:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ACTIVE_RELEASE=${ACTIVE_RELEASE}
    depends_on:
      - app_blue
      - app_green
    volumes:
      - nginx_logs:/var/log/nginx

  alert_watcher:
    build: ./watcher
    container_name: blue-green-alert-watcher
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
    volumes:
      - nginx_logs:/logs:ro
    depends_on:
      - nginx

volumes:
  nginx_logs:
